name: consultation_form_library
description: "Consultation form library."
version: 0.2.0
repository: https://github.com/Tejas-Kotiann/consultationFormLibrary
environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
